export class KpiEntry {
  ac_actionclubquantity: string = "0";
  ac_actionclubtotalamount: number = 0;
  ac_growthclubquantity: string = "0";
  ac_growthclubtotalamount: number = 0;
  ac_planningclubquantity: string = "0";
  ac_planningclubtotalamount: number = 0;
  ac_profitclubquantity: string = "0";
  ac_profitclubtotalamount: number = 0;
  ac_alignrichquantity: string = "0";
  ac_alignrichtotalamount: number = 0;
  ac_businessrichquantity: string = "0";
  ac_businessrichtotalamount: number = 0;
  ac_financerichquantity: string = "0";
  ac_financerichtotalamount: number = 0;
  ac_phonerichquantity: string = "0";
  ac_phonerichtotalamount: number = 0;
  ac_teamrichquantity: string = "0";
  ac_teamrichtotalamount: number = 0;
  ac_timerichquantity: string = "0";
  ac_timerichtotalamount: number = 0;
  ac_salesrichquantity: string = "0";
  ac_salesrichtotalamount: number = 0;
  ac_servicerichquantity: string = "0";
  ac_servicerichtotalamount: number = 0;
  ac_leveragegamenightsquantity: string = "0";
  ac_leveragegamenightstotalamount: number = 0;
  ac_fivewaysseminarquantity: string = "0";
  ac_fivewaysseminartotalamount: number = 0;
  ac_sixstepsseminarquantity: string = "0";
  ac_sixstepsseminartotalamount: number = 0;
  ac_engagegrowquantity: string = "0";
  ac_engagegrowtotalamount: number = 0;
  ac_bucketlistlifequantity: string = "0";
  ac_bucketlistlifetotalamount: number = 0;
  ac_mentorclubquantity: string = "0";
  ac_mentorclubtotalamount: number = 0;
  ac_bookclubquantity: string = "0";
  ac_bookclubtotalamount: number = 0;
  ac_numberofdiagnostics: string = "0";
  ac_numberofleadtotal: string = "0";
  ac_numberofnewclients: string = "0";
  ac_numberofondeckcalls: string = "0";
  ac_numberofmarketingstrategiesused: string = "0";
  ac_totalmarketinginvestment: number = 0;
  "ac_Submitter@odata.bind": string;
  "transactioncurrencyid@odata.bind": string;
  "ownerid@odata.bind": string;
  ac_year: string;
  ac_month: string;
  ac_submissiondate: string;
}

export class CashbankEntry {
  "ac_Submitter@odata.bind": string;
  "transactioncurrencyid@odata.bind": string;
  "ownerid@odata.bind": string;
  ac_amount: number = 0;
  ac_month: string;
  ac_year: string;
  ac_submissiondate: string;
}
